### ISSUE TITLE
Type "re_t_funcincl" is unkown

### ISSUE THREAD

**Issue by jaysonwcs** [abapinho/abapTimeMachine#135]
Tried to install on SAPTrial (NW version 7.52) and got this error.
I believe it could be created a similar Z data element instead of using the standard one.

![image](https://user-images.githubusercontent.com/7007373/231872141-d7c95cb7-9e5d-4374-9ec4-e8fc953123aa.png)

**Comment by nununo** [comment]
Fixed in #137.

**Comment by nununo** [comment]
@jaysonwcs, thank you for reporting this. Interesting that a global type is deleted. I didn't know SAP did that.

I opted to create a local table type in the class instead of a global one in DDIC since it is only used inside that class. Simpler. So I will close your TR. Thank you very much for your correction proposal nevertheless.
